services:
  laravel:
    build:
      context: .
      tags:
        - "laravel-dev-env"
    image: laravel-dev-env
    container_name: laravel-dev-env
    network_mode: "host"
    volumes:
      - ./apps:/var/www:Z
    stdin_open: true
    tty: true

  mysql:
    restart: unless-stopped
    image: mysql:8-debian
    container_name: laravel-mysql
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres:
    restart: unless-stopped
    image: postgres:18-alpine
    container_name: laravel-postgres
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/18/data
    ports:
      - "5432:5432"

volumes:
  mysqldata:
  pgdata:
